spring:
  datasource:
    url: jdbc:mysql://192.168.2.10:24478/resources_class?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: fzsj@GIS
    database: 4
    host: 202.102.89.244

# 跨域
registry:
  allowedOrigins: http://202.102.89.244:88

neo4j:
  url: bolt://127.0.0.1:7687

file:
  root: E:\\e-resource\\TestResource
